# Generated by Django 3.0.5 on 2023-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_massage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
    ]
