# Generated by Django 3.0.5 on 2023-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_massage', '0002_auto_20231107_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='Landlord_phone',
            new_name='landlord_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='home_id',
            new_name='room_num',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='Landlord_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='home_num',
        ),
        migrations.AddField(
            model_name='landlord',
            name='landlord_name',
            field=models.CharField(blank=True, db_column='Landlord_name', max_length=255, null=True, verbose_name='房东姓名'),
        ),
        migrations.AddField(
            model_name='money',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_num',
            field=models.CharField(default=1, max_length=255, verbose_name='门牌号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landlord',
            name='house_number',
            field=models.CharField(default=1, max_length=11, verbose_name='门牌号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landlord',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_phone',
            field=models.IntegerField(db_column='Landlord_phone', verbose_name='房东手机号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='home_id',
            field=models.IntegerField(verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='house_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money',
            name='other',
            field=models.FloatField(verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house_number',
            field=models.CharField(default=1, max_length=255, verbose_name='门牌号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='租金'),
        ),
        migrations.AlterField(
            model_name='user',
            name='check_in_time',
            field=models.DateTimeField(verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(default=1, max_length=255, verbose_name='门牌号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.IntegerField(verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='用户姓名'),
        ),
        migrations.AlterModelTable(
            name='landlord',
            table='Landlord',
        ),
        migrations.AlterModelTable(
            name='money',
            table='Money',
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
