# Generated by Django 3.0.5 on 2023-11-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_massage', '0003_auto_20231107_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='home_id',
        ),
        migrations.AddField(
            model_name='money',
            name='room_num',
            field=models.CharField(default='000', max_length=5, verbose_name='房间号'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='00', max_length=6, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_time',
            field=models.DateField(blank=True, null=True, verbose_name='搬离时间'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='house_number',
            field=models.CharField(max_length=255, null=True, verbose_name='出租门牌号'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_name',
            field=models.CharField(db_column='Landlord_name', max_length=255, null=True, verbose_name='房东姓名'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_phone',
            field=models.CharField(max_length=13, null=True, verbose_name='房东手机号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='house_number',
            field=models.CharField(max_length=255, null=True, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='kwh',
            field=models.FloatField(null=True, verbose_name='用电量'),
        ),
        migrations.AlterField(
            model_name='money',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='money',
            name='rent_time',
            field=models.DateField(null=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='money',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='房租'),
        ),
        migrations.AlterField(
            model_name='money',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='money',
            name='water_content',
            field=models.FloatField(null=True, verbose_name='用水量'),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.CharField(max_length=11, null=True, verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house_number',
            field=models.CharField(max_length=255, null=True, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='power_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='电费'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_num',
            field=models.CharField(max_length=255, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.CharField(max_length=11, null=True, verbose_name='房租'),
        ),
        migrations.AlterField(
            model_name='room',
            name='water_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='水费'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='user',
            name='check_in_time',
            field=models.DateField(db_column='check-in_time', verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=6, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(max_length=255, null=True, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.BigIntegerField(null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=255, null=True, verbose_name='工作'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_num',
            field=models.CharField(max_length=5, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=13, null=True, verbose_name='手机号'),
        ),
        migrations.AlterModelTable(
            name='landlord',
            table='landlord',
        ),
        migrations.AlterModelTable(
            name='money',
            table='money',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
