# Generated by Django 3.0.5 on 2023-11-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_massage', '0004_auto_20231116_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='room_num',
            field=models.CharField(max_length=5, null=True, verbose_name='房间号'),
        ),
    ]
