# Generated by Django 3.0.5 on 2023-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_massage', '0006_auto_20231116_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='landlord',
            name='password',
            field=models.CharField(default=0, max_length=8, verbose_name='登录密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landlord',
            name='house_number',
            field=models.CharField(max_length=255, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_name',
            field=models.CharField(db_column='Landlord_name', max_length=255, verbose_name='房东姓名'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_phone',
            field=models.CharField(max_length=13, verbose_name='房东手机号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='house_number',
            field=models.CharField(max_length=255, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='kwh',
            field=models.FloatField(verbose_name='当前用电量'),
        ),
        migrations.AlterField(
            model_name='money',
            name='rent_time',
            field=models.DateField(verbose_name='出租时间'),
        ),
        migrations.AlterField(
            model_name='money',
            name='room_num',
            field=models.CharField(max_length=5, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='money',
            name='room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='租金'),
        ),
        migrations.AlterField(
            model_name='money',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='money',
            name='water_content',
            field=models.FloatField(verbose_name='当前用水量'),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.CharField(max_length=11, verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house_number',
            field=models.CharField(max_length=255, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='room',
            name='power_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='水费'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_num',
            field=models.CharField(max_length=255, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.CharField(max_length=11, verbose_name='租金'),
        ),
        migrations.AlterField(
            model_name='room',
            name='water_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='电费'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=6, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='check_in_time',
            field=models.DateTimeField(db_column='check-in_time', verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(max_length=255, verbose_name='门牌号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.BigIntegerField(verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=255, verbose_name='工作'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leave_time',
            field=models.DateField(blank=True, null=True, verbose_name='退租时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_num',
            field=models.CharField(max_length=5, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=13, verbose_name='手机号'),
        ),
    ]
